const {
  PORT,
  NODE_ENV,
  DEBUG_LEVEL,
  BASE_URL,
  SSL_CERT_PATH,
  SSL_KEY_PATH,
  WEBPAY_COMMERCE_CODE,
  WEBPAY_COMMERCE_CERT_PATH,
  WEBPAY_COMMERCE_KEY_PATH,
} = process.env;

export {
  PORT,
  NODE_ENV,
  DEBUG_LEVEL,
  BASE_URL,
  SSL_CERT_PATH,
  SSL_KEY_PATH,
  WEBPAY_COMMERCE_CODE,
  WEBPAY_COMMERCE_CERT_PATH,
  WEBPAY_COMMERCE_KEY_PATH,
};
